### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by gopala000** [soukoku/vue-oidc-client#44]
I want to try the sample vue app to use with identity server. When I run npm install, I get the following error. How to I get around with this? Thanks

C:\Users\foo\source\repos\vue-oidc-client>npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: vue-oidc-client@0.4.2
npm ERR! Found: eslint@7.2.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.0.0 || ^6.0.0" from eslint-plugin-vue@6.2.2
npm ERR! node_modules/eslint-plugin-vue
npm ERR!   dev eslint-plugin-vue@"^6.2.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\foo\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\foo\AppData\Local\npm-cache\_logs\2021-04-04T18_19_51_495Z-debug.log

**Comment by soukoku** [comment]
I've fixed it so it doesn't have this error on npm v7, but this repo was made using yarn so not sure how well it really works.

**Comment by gopala000** [comment]
Thanks, @soukoku. That error is fixed. Now, when I run the server using **npm run serve**, I get below error:

```
C:\Users\foo\source\repos\vue-oidc-client\sample>npm run serve

> vue-oidc-client-sample@0.1.0 serve
> vue-cli-service serve

 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 errors                                                                      12:45:17 PM

 error  in ./src/main.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Invariant Violation: [BABEL] C:\Users\foo\source\repos\vue-oidc-client\sample\src\main.js: Invalid Option: The plugins/built-ins 'es.array.iterator, es.promise, es.object.assign, es.promise.finally' passed to the 'exclude' option are not
    valid. Please check data/[plugin-features|built-in-features].js in babel-preset-env (While processing: "C:\\Users\\foo\\source\\repos\\vue-oidc-client\\sample\\node_modules\\@vue\\babel-preset-app\\index.js.overrides[0]$0")
    at invariant (C:\Users\foo\source\repos\vue-oidc-client\sample\node_modules\invariant\invariant.js:40:15)
    at expandIncludesAndExcludes (C:\Users\foo\source\repos\vue-oidc-client\sample\node_modules\@babel\preset-env\lib\normalize-options.js:64:26)
    at normalizeOptions (C:\Users\foo\source\repos\vue-oidc-client\sample\node_modules\@babel\preset-env\lib\normalize-options.js:180:19)
    at C:\Users\foo\source\repos\vue-oidc-client\sample\node_modules\@babel\preset-env\lib\index.js:239:37
    at C:\Users\foo\source\repos\vue-oidc-client\sample\node_modules\@babel\helper-plugin-utils\lib\index.js:19:12
    at C:\Users\foo\source\repos\vue-oidc-client\sample\node_modules\@babel\core\lib\config\full.js:199:14
    at Generator.next (<anonymous>)
    at Function.<anonymous> (C:\Users\foo\source\repos\vue-oidc-client\sample\node_modules\@babel\core\lib\gensync-utils\async.js:26:3)
    at Generator.next (<anonymous>)
    at step (C:\Users\foo\source\repos\vue-oidc-client\sample\node_modules\gensync\index.js:254:32)
    at evaluateAsync (C:\Users\foo\source\repos\vue-oidc-client\sample\node_modules\gensync\index.js:284:5)
    at Function.errback (C:\Users\foo\source\repos\vue-oidc-client\sample\node_modules\gensync\index.js:108:7)
    at errback (C:\Users\foo\source\repos\vue-oidc-client\sample\node_modules\@babel\core\lib\gensync-utils\async.js:70:18)
    at async (C:\Users\foo\source\repos\vue-oidc-client\sample\node_modules\gensync\index.js:183:31)
    at onFirstPause (C:\Users\foo\source\repos\vue-oidc-client\sample\node_modules\gensync\index.js:209:13)
    at Generator.next (<anonymous>)

 @ multi (webpack)-dev-server/client?http://192.168.86.238:8081&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```
